version: "3"
services:
# リバプロ
  reverse:
    image: nginx:latest
    # container_name: 'reverse'
    privileged: true
    volumes:
      - ./logs/reverse:/var/log/nginx
      - ./docker/reverse/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    restart: always
# webserver  
  web1:
    image: nginx:latest
    depends_on:
      - app
    # container_name: "web1"
    volumes:
      - ./src:/work
      - ./logs/web1:/var/log/nginx
      - ./docker/web1/proxy.conf:/etc/nginx/conf.d/proxy.conf
    environment:
      VIRTUAL_HOST: 'app1.test'
      LETSENCRYPT_HOST: 'app1.test'
      LETSENCRYPT_EMAIL: 'example@app1.test'
    # environment:
    #   - TZ=${TZ}


# php
  app:
    build:
      context: ./docker/php
      args:
        - TZ=${TZ}
    volumes:
      - ./src:/work
      - ./logs/php:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /work
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - TZ=${TZ}
      
networks:
  default:
    external:
      name: shared
