version: "3"
services:
# リバプロ
  reverse:
    image: nginx:latest
    container_name: 'reverse'
    privileged: true
    volumes:
      - ./docker/reverse/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    restart: always
  
  web1:
    image: nginx:latest
    container_name: "web1"
    volumes:
      - ./src/web1/public:/app
      - ./docker/web1/proxy.conf:/etc/nginx/conf.d/proxy.conf
    environment:
      VIRTUAL_HOST: 'app1.test'
      LETSENCRYPT_HOST: 'app1.test'
      LETSENCRYPT_EMAIL: 'example@app1.test'

networks:
  default:
    external:
      name: shared
