version: "3"
services:
  app:
    image: nginx:latest
    container_name: "app"
    ports:
      - "8080:80"
    volumes:
      - ./nginx/html:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf


